model:
  embed_size: 512
  hidden_size: 512
  num_layers: 1

attn_model:
  num_heads: 4
  dropout: 0.1
  max_length: 40

training:
  learning_rate: 0.001
  num_epochs: 50
  num_workers: 2
  batch_size: 64
  test_ratio: 0.05
  val_ratio: 0.1

checkpoint:
  load_model: false
  save_model: true