training:

  # learning settings
  learning_rate: 0.005
  step_size: 5
  gamma: 0.8
  num_epochs: 50

  # dataset settings
  num_workers: 2
  batch_size: 64
  val_ratio: 0.1
  test_ratio: 0.05
  
  # model settings
  model_arch: 'cnn-rnn' # 'cnn-rnn' or 'cnn-attn'
  dataset: 'mscoco' # 'mscoco' or 'flickr'
  inference_type: 'greedy'

# specify the model hyperparameters

# CNN-RNN model
rnn_model:
  embed_size: 512
  hidden_size: 512

# CNN-Attention model
attn_model:
  embed_size: 512
  num_layers: 8
  num_heads: 8