training:

  # learning settings
  learning_rate: 0.001
  step_size: 5
  gamma: 0.8
  num_epochs: 50

  # dataset settings
  num_workers: 2
  batch_size: 64
  val_ratio: 0.1
  test_ratio: 0.05
  
  # model settings
  model_arch: 'cnn-rnn' # 'cnn-rnn' or 'cnn-attn' or 'yolovae-attn'
  dataset: 'flickr' # 'mscoco' or 'flickr'
  mode: 'image' # 'precomputed' or 'image'
  inference_type: 'greedy' # 'greedy' or 'beam'
  beam_width: 3

  # save and load checkpoints
  save_model: false
  load_model: false
  checkpoint_dir: './checkpoints/checkpoint_epoch_50.pth.tar'

# specify the model hyperparameters

# CNN-RNN model
rnn_model:
  embed_size: 512
  hidden_size: 512

# CNN-Attention model
attn_model:
  embed_size: 512
  num_layers: 2
  num_heads: 4

yolovae_attn_model:
  embed_size: 512
  num_layers: 2
  num_heads: 4